=== martin-lemay/pyWellSFM/jsonSchemas/DepositionalEnvironmentModelSchema.json
{
    "$schema": "http://json-schema.org/draft/2020-12/schema",
    "$id": "https://raw.githubusercontent.com/martin-lemay/pyWellSFM/main/jsonSchemas/DepositionalEnvironmentModelSchema.json",
    "title": "Depositional Environment model Schema",
    "description": "Defines the input data for a depositional environment model.",
    "type": "object",
    "properties": {
        "format": {
            "description": "Defines the file content for verification purposes.",
            "const": "pyWellSFM.DepositionalEnvironmentModelSchema"
        },
        "version": {
            "description": "Defines the file content version.",
            "const": "1.0"
        },
        "name": {
            "description": "Name of the depositional environment model.",
            "type": "string"
        },
        "environments" : {
            "description": "Defines the parameters for the depositional environment model.",
            "type": "array",
            "minItems": 1,
            "items": {
                "type": "object",
                "$ref": "#/$defs/DepositionalEnvironment"
            }
        }
    },
    "required": ["format", "version", "name", "environments"],
    "additionalProperties": false,
    "$defs": {
        "DepositionalEnvironment": {
            "type": "object",
            "properties": {
                "name": {
                    "description": "Name of the depositional environment.",
                    "type": "string"
                },
                "description": {
                    "description": "Description of the depositional environment.",
                    "type": "string"
                },
                "waterDepthModel": {
                    "description": "Environment condition model for water depth. Should be statistic model.",
                    "$ref": "https://raw.githubusercontent.com/martin-lemay/pyWellSFM/main/jsonSchemas/EnvironmentConditionModelSchema.json"
                },
                "environmentConditionsModel": {
                    "description": "EnvironmentConditionsModel for additional properties (e.g., energy, temperature).",
                    "type": "object",
                    "$ref": "https://raw.githubusercontent.com/martin-lemay/pyWellSFM/main/jsonSchemas/EnvironmentConditionsModelSchema.json"
                },
                "distality": {
                    "description": "Distality of the depositional environment (between 0 and 1, where 0 is proximal and 1 is distal).",
                    "type": "number"
                }
            },
            "required": ["name", "waterDepthModel"],
            "additionalProperties": false
        }
    }
}

=== martin-lemay/pyWellSFM/tests/data/schema_examples/depositional_environment_model_example.json
{
  "format": "pyWellSFM.DepositionalEnvironmentModelSchema",
  "version": "1.0",
  "name": "DepositionalEnvExample",
  "environments": [
    {
      "name": "Lagoon",
      "waterDepthModel": {
        "format": "pyWellSFM.EnvironmentConditionModelData",
        "version": "1.0",
        "model": {
          "modelType": "Uniform",
          "minValue": 0.0,
          "maxValue": 10.0
        }
      },
      "environmentConditionsModel": {
        "format": "pyWellSFM.EnvironmentConditionsModelData",
        "version": "1.0",
        "environmentConditions": {
          "energy": {
            "format": "pyWellSFM.EnvironmentConditionModelData",
            "version": "1.0",
            "model": {
              "modelType": "Constant",
              "value": 0.25
            }
          }
        }
      },
      "distality": 0.2
    }
  ]
}
