=== martin-lemay/pyWellSFM/jsonSchemas/RealizationDataSchema.json
{
    "$schema": "http://json-schema.org/draft/2020-12/schema",
    "$id": "https://raw.githubusercontent.com/martin-lemay/pyWellSFM/main/jsonSchemas/RealizationData.json",
    "title": "Input Realization Data",
    "description": "Defines the input data to create a realization data object.",
    "type": "object",
    "properties": {
        "format": {
            "description": "Defines the file content for verification purposes.",
            "const": "pyWellSFM.RealizationData"
        },
        "version": {
            "description": "Defines the file content version.",
            "const": "1.0"
        },
        "well": {
            "oneOf": [
                {
                    "description": "Inline well definition.",
                    "$ref": "https://raw.githubusercontent.com/martin-lemay/pyWellSFM/main/jsonSchemas/WellSchema.json"
                },
                {
                    "type": "object",
                    "description": "Path to a well file.",
                    "properties": {
                        "url": {
                            "type": "string",
                            "description": "Relative or absolute path to the well file."
                        }
                    },
                    "required": [
                        "url"
                    ],
                    "additionalProperties": false
                }
            ]
        },
        "initialBathymetry": { 
            "type": "number",
            "description": "Initial bathymetry at the well location (in meters)."
        },
        "subsidenceCurve": {
            "type": "object",
            "description": "Subsidence curve.",
            "properties": {
                "type": {
                    "type": "string",
                    "enum": ["cumulative", "rate"],
                    "description": "Type of subsidence values: Either 'cumulative' or 'rate'."
                },
                "curve": {
                    "oneOf": [
                        {
                            "description": "Inline curve definition.",
                            "$ref": "https://raw.githubusercontent.com/martin-lemay/pyWellSFM/main/jsonSchemas/CurveSchema.json"
                        },
                        {
                            "type": "object",
                            "description": "Path to a curve.",
                            "properties": {
                                "url": {
                                    "type": "string",
                                    "description": "Relative or absolute path to the curve file."
                                }
                            },
                            "required": [
                                "url"
                            ],
                            "additionalProperties": false
                        }
                    ]
                }
            },
            "required": [
                "type",
                "curve"
            ],
            "additionalProperties": false
        }
    },
    "required": [
        "format",
        "version",
        "well",
        "initialBathymetry"
    ],
    "additionalProperties": false
}

=== martin-lemay/pyWellSFM/tests/data/schema_examples/realization_data_example.json
{
  "format": "pyWellSFM.RealizationData",
  "version": "1.0",
  "well": {
    "format": "pyWellSFM.WellData",
    "version": "1.0",
    "well": {
      "name": "RealizationWellInline",
      "location": {"x": 1.0, "y": 1.0, "z": 0.0},
      "depth": 120.0
    }
  },
  "initialBathymetry": 15.0,
  "subsidenceCurve": {
    "type": "cumulative",
    "curve": {
      "format": "pyWellSFM.CurveData",
      "version": "1.0",
      "curve": {
        "xAxisName": "Age",
        "yAxisName": "Subsidence",
        "interpolationMethod": "linear",
        "data": [
          {"x": 0.0, "y": 0.0},
          {"x": 10.0, "y": 50.0}
        ]
      }
    }
  }
}
