=== martin-lemay/pyWellSFM/jsonSchemas/ScenarioSchema.json
{
    "$schema": "http://json-schema.org/draft/2020-12/schema",
    "$id": "https://raw.githubusercontent.com/martin-lemay/pyWellSFM/main/jsonSchemas/Scenario.json",
    "title": "Input Scenario Data",
    "description": "Defines the input data to create a scenario data object.",
    "type": "object",
    "properties": {
        "format": {
            "description": "Defines the file content for verification purposes.",
            "const": "pyWellSFM.ScenarioData"
        },
        "version": {
            "description": "Defines the file content version.",
            "const": "1.0"
        },
        "name": {
            "description": "Name of the scenario.",
            "type": "string"
        },
        "accumulationModel": {
            "oneOf": [
                {
                    "description": "Inline accumulation model definition.",
                    "$ref": "https://raw.githubusercontent.com/martin-lemay/pyWellSFM/main/jsonSchemas/AccumulationModel.json"
                },
                {
                    "type": "object",
                    "description": "Path to accumulation model JSON file.",
                    "properties": {
                        "url": {
                            "type": "string",
                            "description": "Relative or absolute path to the accumulation model JSON file."
                        }
                    },
                    "required": [
                        "url"
                    ],
                    "additionalProperties": false
                }
            ]
        },
        "depositionalEnvironmentModel": {
            "oneOf": [
                {
                    "description": "Inline depositional environment model definition.",
                    "$ref": "https://raw.githubusercontent.com/martin-lemay/pyWellSFM/main/jsonSchemas/DepositionalEnvironmentModelSchema.json"
                },
                {
                    "type": "object",
                    "description": "Path to depositional environment model JSON file.",
                    "properties": {
                        "url": {
                            "type": "string",
                            "description": "Relative or absolute path to the depositional environment model JSON file."
                        }
                    },
                    "required": [
                        "url"
                    ],
                    "additionalProperties": false
                }
            ]
        },
        "eustaticCurve": {
            "oneOf": [
                {
                    "description": "Inline curve definition.",
                    "$ref": "https://raw.githubusercontent.com/martin-lemay/pyWellSFM/main/jsonSchemas/CurveSchema.json"
                },
                {
                    "type": "object",
                    "description": "Path to a curve.",
                    "properties": {
                        "url": {
                            "type": "string",
                            "description": "Relative or absolute path to the curve file."
                        }
                    },
                    "required": [
                        "url"
                    ],
                    "additionalProperties": false
                }
            ]
        }
    },
    "required": [
        "format",
        "version",
        "name",
        "accumulationModel"
    ],
    "additionalProperties": false
}

=== martin-lemay/pyWellSFM/tests/data/schema_examples/scenario_example.json
{
  "format": "pyWellSFM.ScenarioData",
  "version": "1.0",
  "name": "ScenarioInline",
  "accumulationModel": {
    "format": "pyWellSFM.AccumulationModelData",
    "version": "1.0",
    "accumulationModel": {
      "name": "ScenarioAccModel",
      "elements": {
        "sand": {
          "accumulationRate": 100.0,
          "model": {
            "modelType": "Gaussian",
            "stddevFactor": 0.2
          }
        }
      }
    }
  },
  "eustaticCurve": {
    "format": "pyWellSFM.CurveData",
    "version": "1.0",
    "curve": {
      "xAxisName": "Age",
      "yAxisName": "Eustatism",
      "interpolationMethod": "linear",
      "data": [
        {"x": 0.0, "y": 0.0},
        {"x": 10.0, "y": 5.0}
      ]
    }
  }
}
